name: macOS

on:
  workflow_dispatch:
  push:
      paths:
          - "**"
          - "!.github/**"
          - ".github/workflows/ci.yml"
          - "!**.md"
  
  pull_request:
      paths:
          - "**"
          - "!.github/**"
          - ".github/workflows/ci.yml"
          - "!**.md"

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install macOS dependencies
      run: |
        echo "No requirements"
        #brew update
        #brew install autoconf automake openssl libelf ncurses zlib gmp wget pkg-config

    - name: Runs all the stages in the shell
      run: |
        cd extractps3iso
        make
        cd ../makeps3iso
        make
        cd ../patchps3iso
        make
        cd ../splitps3iso
        make
        cd ..

    - name: Get short SHA
      id: slug
      run: echo "{SHORT_SHA}={sha8::$(echo ${GITHUB_SHA} | cut -c1-8)}" >> $GITHUB_OUTPUT
    
    - name: Compress output
      run: |
        tar -zcvf ps3iso-utils.tar.gz extractps3iso/extractps3iso makeps3iso/makeps3iso patchps3iso/patchps3iso splitps3iso/splitps3iso

    - uses: actions/upload-artifact@v4
      with:
        name: build-${SHORT_SHA}-macOS
        path: ps3iso-utils.tar.gz
